# Generated by Django 4.2.18 on 2025-01-15 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{11}$')]),
        ),
    ]
